#!/usr/bin/env bash
# Rebuilds the inlined Tailwind CSS in universal_scoreboard_pwa.html.
# Run after changing any Tailwind class names in the HTML/JS. Requires Node.
#   ./build.sh
set -euo pipefail
cd "$(dirname "$0")"
HTML=universal_scoreboard_pwa.html
TMP=$(mktemp -d)
cat > "$TMP/tailwind.config.js" <<CFG
module.exports = { content: ['$PWD/$HTML'], corePlugins: { preflight: true } };
CFG
printf '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n' > "$TMP/in.css"
npx --yes tailwindcss@3 -c "$TMP/tailwind.config.js" -i "$TMP/in.css" -o "$TMP/out.css" --minify >/dev/null 2>&1
# Splice: replace everything between the markers with the fresh CSS.
python3 - "$HTML" "$TMP/out.css" <<'PY'
import sys, re
html_path, css_path = sys.argv[1], sys.argv[2]
html = open(html_path).read()
css = open(css_path).read().strip()
block = '<!-- TAILWIND:BEGIN (generated by build.sh, do not edit) -->\n  <style>' + css + '</style>\n  <!-- TAILWIND:END -->'
if '<!-- TAILWIND:BEGIN' in html:
    html = re.sub(r'<!-- TAILWIND:BEGIN.*?<!-- TAILWIND:END -->', block, html, flags=re.S)
else:
    html = html.replace('<!--TAILWIND_CSS-->', block)
open(html_path, 'w').write(html)
print('inlined', len(css), 'bytes of CSS')
PY
rm -rf "$TMP"
